// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPolutionMonitoring.proto

package grpc.examples.SmartAir;

public interface AirQualityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartAir.AirQualityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room = 1;</code>
   */
  java.lang.String getRoom();
  /**
   * <code>string room = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomBytes();
}
