// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPolutionMonitoring.proto

package grpc.examples.SmartAir;

public interface AirQualityReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartAir.AirQualityReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 quality = 1;</code>
   */
  int getQuality();
}
