// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPolutionMonitoring.proto

package grpc.examples.SmartAir;

public interface AllAirQualityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartAir.AllAirQualityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string allRoom = 1;</code>
   */
  java.lang.String getAllRoom();
  /**
   * <code>string allRoom = 1;</code>
   */
  com.google.protobuf.ByteString
      getAllRoomBytes();
}
