// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPurificationSystem.proto

package grpc.examples.SmartAir;

public interface ChangeSpeedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartAir.ChangeSpeedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string speed = 1;</code>
   */
  java.lang.String getSpeed();
  /**
   * <code>string speed = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpeedBytes();
}
