// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPurificationSystem.proto

package grpc.examples.SmartAir;

public interface ChangeSpeedReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartAir.ChangeSpeedReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string speed = 1;</code>
   */
  java.lang.String getSpeed();
  /**
   * <code>string speed = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpeedBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
