// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPolutionSystemLogin.proto

package grpc.examples.SmartAir;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartAir.Empty)
    com.google.protobuf.MessageOrBuilder {
}
