// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPolutionSystemLogin.proto

package grpc.examples.SmartAir;

public final class SmartAirLoginImpl {
  private SmartAirLoginImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_UserLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_UserLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_UserLoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_UserLoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_UserLogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_UserLogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_UserLogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_UserLogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034AirPolutionSystemLogin.proto\022\010SmartAir" +
      "\".\n\020UserLoginRequest\022\014\n\004name\030\001 \001(\t\022\014\n\004pa" +
      "ss\030\002 \001(\t\"B\n\021UserLoginResponse\022\027\n\017respons" +
      "eMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"!\n\021" +
      "UserLogoutRequest\022\014\n\004name\030\001 \001(\t\"C\n\022UserL" +
      "ogoutResponse\022\027\n\017responseMessage\030\001 \001(\t\022\024" +
      "\n\014responseCode\030\002 \001(\005\"\007\n\005Empty2\245\001\n\020UserLo" +
      "ginService\022F\n\tUserLogin\022\032.SmartAir.UserL" +
      "oginRequest\032\033.SmartAir.UserLoginResponse" +
      "\"\000\022I\n\nUserLogout\022\033.SmartAir.UserLogoutRe" +
      "quest\032\034.SmartAir.UserLogoutResponse\"\000B-\n" +
      "\026grpc.examples.SmartAirB\021SmartAirLoginIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartAir_UserLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartAir_UserLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_UserLoginRequest_descriptor,
        new java.lang.String[] { "Name", "Pass", });
    internal_static_SmartAir_UserLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartAir_UserLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_UserLoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_SmartAir_UserLogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartAir_UserLogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_UserLogoutRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_SmartAir_UserLogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartAir_UserLogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_UserLogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_SmartAir_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartAir_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
