// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPurificationSystem.proto

package grpc.examples.SmartAir;

public final class SmartAirSystemImpl {
  private SmartAirSystemImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_ChangeSpeedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_ChangeSpeedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_ChangeSpeedReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_ChangeSpeedReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033AirPurificationSystem.proto\022\010SmartAir\"" +
      "#\n\022ChangeSpeedRequest\022\r\n\005speed\030\001 \001(\t\"7\n\020" +
      "ChangeSpeedReply\022\r\n\005speed\030\001 \001(\t\022\024\n\014respo" +
      "nseCode\030\002 \001(\0052b\n\025AirPurificationSystem\022I" +
      "\n\013ChangeSpeed\022\034.SmartAir.ChangeSpeedRequ" +
      "est\032\032.SmartAir.ChangeSpeedReply\"\000B.\n\026grp" +
      "c.examples.SmartAirB\022SmartAirSystemImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartAir_ChangeSpeedRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartAir_ChangeSpeedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_ChangeSpeedRequest_descriptor,
        new java.lang.String[] { "Speed", });
    internal_static_SmartAir_ChangeSpeedReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartAir_ChangeSpeedReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_ChangeSpeedReply_descriptor,
        new java.lang.String[] { "Speed", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
