// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPolutionMonitoring.proto

package grpc.examples.SmartAir;

public final class SmartAirServiceImpl {
  private SmartAirServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_AirQualityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_AirQualityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_AllAirQualityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_AllAirQualityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_AirQualityReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_AirQualityReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartAir_AveAirQualityReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartAir_AveAirQualityReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033AirPolutionMonitoring.proto\022\010SmartAir\"" +
      "!\n\021AirQualityRequest\022\014\n\004room\030\001 \001(\t\"\'\n\024Al" +
      "lAirQualityRequest\022\017\n\007allRoom\030\001 \001(\t\"\"\n\017A" +
      "irQualityReply\022\017\n\007quality\030\001 \001(\005\"%\n\022AveAi" +
      "rQualityReply\022\017\n\007quality\030\001 \001(\0052\335\002\n\026AirPo" +
      "llutionMonitoring\022J\n\016RoomAirQuality\022\033.Sm" +
      "artAir.AirQualityRequest\032\031.SmartAir.AirQ" +
      "ualityReply\"\000\022R\n\021AllRoomAirQuality\022\036.Sma" +
      "rtAir.AllAirQualityRequest\032\031.SmartAir.Ai" +
      "rQualityReply\"\0000\001\022O\n\017RoomsAirQuality\022\033.S" +
      "martAir.AirQualityRequest\032\031.SmartAir.Air" +
      "QualityReply\"\000(\0010\001\022R\n\021AveRoomAirQuality\022" +
      "\033.SmartAir.AirQualityRequest\032\034.SmartAir." +
      "AveAirQualityReply\"\000(\001B/\n\026grpc.examples." +
      "SmartAirB\023SmartAirServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartAir_AirQualityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartAir_AirQualityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_AirQualityRequest_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_SmartAir_AllAirQualityRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartAir_AllAirQualityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_AllAirQualityRequest_descriptor,
        new java.lang.String[] { "AllRoom", });
    internal_static_SmartAir_AirQualityReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartAir_AirQualityReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_AirQualityReply_descriptor,
        new java.lang.String[] { "Quality", });
    internal_static_SmartAir_AveAirQualityReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartAir_AveAirQualityReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartAir_AveAirQualityReply_descriptor,
        new java.lang.String[] { "Quality", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
