// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPolutionSystemLogin.proto

package grpc.examples.SmartAir;

public interface UserLogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartAir.UserLogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
